### ISSUE TITLE
Create a chapter for the master to devel transition in https://contributions.bioconductor.org

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/pkgrevdocs#80] opened 2022-11-30 19:19 UTC

**Comment by kevinrue** [comment] 2022-11-30 20:07
duplicate of #79

**Comment by LiNk-NY** [comment] 2022-11-30 21:53
@kevinrue 
It's not, there is a difference

**Comment by kevinrue** [comment] 2022-11-30 22:38
Ahhh ok, sorry!

**Comment by LiNk-NY** [comment] 2023-01-05 15:56
https://github.com/Bioconductor/pkgrevdocs/pull/84

**Closed** 2023-01-19 13:12 UTC
Labels: documentation
